### ISSUE TITLE
TypeScriptify codebase

### ISSUE THREAD

**Issue by inakianduaga** [Scout24/toguru-client-nodejs#3]
# TODO

- [x] Convert files to TypeScript, update module export syntax and add basic type definitions       
- [ ] Update tests to typescript and have them pass
- [ ] Refactor and simplify functions
- [ ] Add tslint and fix linting errors
- [ ] Add build system and npm publishing using travisCI (can rip off https://github.com/Scout24/as24-custom-events)

**Comment by sgeb** [comment]
@Scout24/as24-cxp-acquisition: can you please add this to your backlog and discuss when is a realistic time to get this done? Thanks.

**Comment by inakianduaga** [comment]
@sgeb This is 1/2 there, codebase is 99% typescriptified

https://github.com/Scout24/toguru-client-nodejs/tree/typescript_support

The thing to do would be to improve the API itself and the internal implementation has a lot of room for improvement. Even if the first iteration leaves the internal implementation mostly as is (since that's an implementation detail that can be improved on a follow up release), the public API should be more polished since that's what all services are going to use. 

I'm happy to take part of the process, in fact I would probably finish the first draft if I would have a couple of hours.

**Comment by omakoleg** [comment]
@inakianduaga any plans to finish this ?

**Comment by inakianduaga** [comment]
@omakoleg Yes, I'll put some time into this in the next couple of weeks so we can finish it.

**Comment by inakianduaga** [comment]
done in #20 !
